# Generated by Django 2.1.2 on 2018-10-19 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed_file', max_length=32)),
                ('mime', models.CharField(max_length=72)),
                ('key', models.CharField(max_length=72)),
                ('content', models.FileField(null=True, upload_to='files')),
                ('owners', models.ManyToManyField(related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
