"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vxdfssavfm11i7*z)4@=jwa%=*wftsyvj2^*tc2f*v*&o0g5$z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'comments.apps.CommentsConfig',
    'core.apps.CoreConfig',
    'categories.apps.CategoriesConfig',
    'users.apps.UsersConfig',
    'topics.apps.TopicsConfig',
    'likes.apps.LikesConfig',
    'crispy_forms',
    'debug_toolbar',
    'social_django',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.vk.VKOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

INTERNAL_IPS = [
    '127.0.0.1'
]

CASHES = {
    'default' : {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'core.context_processors.main',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST')
    }
}

TESTING = 'test' in sys.argv

if TESTING:
    DATABASES['default'] = {'ENGINE': 'django.db.backends.sqlite3'}



# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = 'core:login'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# STATICFILES_STORAGE = 'django.core.files.storage.FileSystemStorage'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_S3_ENDPOINT_URL = 'http://hb.bizmrg.com/'
AWS_ACCESS_KEY_ID = 'quZTPp3V28P7V1SGJRXxvs'
AWS_SECRET_ACCESS_KEY = '7arUgwahLMmhHpreUJh9RTkHB7LdD5UNcTjA5VLSP59G'
AWS_STORAGE_BUCKET_NAME = 'miptoverflow'

SOCIAL_AUTH_VK_OAUTH2_KEY = '6727578'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'HFne4archRbNZjxmSAeJ'
SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email']

SOCIAL_AUTH_GITHUB_KEY = 'e7d317813754050bab3c'
SOCIAL_AUTH_GITHUB_SECRET = '48c52cb81e18b4df36e289610deaa99ddf11a21f'
SOCIAL_AUTH_GITHUB_SCOPE = ['email']

LOGIN_REDIRECT_URL = '/'

CENTRIFUGE_ADDRESS = 'http://localhost:9000'
CENTRIFUGE_SECRET = '09a3bbb7-8b2b-445b-b1f4-7913287a3ea5'
CENTRIFUGE_API_KEY = '1erj444h-9fhj-pasd-oas4-988f33d33d21'
CENTRIFUGE_TIMEOUT = 5